name: check

on:
  push:
    branches-ignore: main

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml

  build:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-nodemodules
      - uses: actions/cache@v4
        id: build-cache
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-next-build-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-next-build-
      - name: Run build
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: yarn turbo build
        env:
          NEXT_PUBLIC_AIRTABLE_API_KEY: ${{ secrets.NEXT_PUBLIC_AIRTABLE_API_KEY }}
          NEXT_PUBLIC_AIRTABLE_BASE_INQUIRYFORM: ${{ secrets.NEXT_PUBLIC_AIRTABLE_BASE_INQUIRYFORM }}
          NEXT_PUBLIC_AIRTABLE_TABLE_INQUIRYFORM: ${{ secrets.NEXT_PUBLIC_AIRTABLE_TABLE_INQUIRYFORM }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
